<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>bash the drum. to the beat.</Description>
    <Version>2026.509.0-ppdev</Version>
    <Authors>ppy Pty Ltd, GooGuTeam</Authors>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
    <Title>osu!taiko (ruleset)</Title>
    <PackageId>g0v0.osu.Game.Rulesets.Taiko</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\osu.Game\osu.Game.csproj" />
  </ItemGroup>
</Project>
