// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

namespace osu.Game.Mapperatorinator
{
    /// <summary>
    /// The user_tags descriptor vocabulary the v32 model family understands.
    /// Generated from datasets/tags_2026.json in the Mapperatorinator repo; regenerate
    /// when the tool updates its tag list.
    /// </summary>
    public static class MapperatorinatorDescriptors
    {
        /// <param name="Name">Full tag, e.g. "style/clean".</param>
        /// <param name="Description">Tooltip text, straight from the tool's dataset.</param>
        /// <param name="RulesetId">Gamemode it applies to; null = all modes.</param>
        public record Descriptor(string Name, string Description, int? RulesetId);

        public static readonly Descriptor[] ALL =
        {
            new Descriptor("additions/combo colours", "Maps that adjust combo colours in conjunction with variations in the song, also referred to as colourhax.", 0),
            new Descriptor("additions/custom skin", "Utilizes custom skin elements and graphics.", null),
            new Descriptor("additions/hitsounds", "A map that makes use of non-default hitsound samplesets.", 1),
            new Descriptor("additions/keysounds", "Contains hitsounds that use various pitched samples to create a melody, typically following one within the song.", null),
            new Descriptor("context/custom song", "Maps a song made specifically for the map. This includes songs created for a mapping contest which the map participated in.", null),
            new Descriptor("context/mapping contest", "An entry for a mapping contest.", null),
            new Descriptor("context/tournament custom", "A map created for a playing tournament.", null),
            new Descriptor("expression/chaotic", "Unpredictable map design, often testing unusual skillsets.", 0),
            new Descriptor("expression/conceptual", "Distinct map design choices that do not follow ordinary mapping conventions, typically to creatively express part of a song.", null),
            new Descriptor("expression/difficulty spike", "Contains a sudden and significant increase in challenge within the map's gameplay.", null),
            new Descriptor("expression/high contrast", "Uses flashy ideas to follow changes in the music, creating stark differences between different sections of the song.", null),
            new Descriptor("expression/iNiS-style", "A style originating from the original DS games, recognizable by its emphasis on vocal rhythm, constant slider velocity, and easily understandable grid-snapped patterns.", 0),
            new Descriptor("expression/improvisation", "Uses patterns that do not correspond to sounds in the music, often using hitsounds to add sounds in.", 0),
            new Descriptor("expression/improvisation", "A map that's based on full improvisation that works as additional layer to the song.", 1),
            new Descriptor("expression/inspo", "Maps that draw inspiration directly from other maps/mappers.", null),
            new Descriptor("expression/old-style revival", "Emulates a style closely associated with early mapping, typically to pay homage or invoke nostalgia.", 0),
            new Descriptor("expression/playfield usage", "Includes deliberate use of the playfield within the map design.", 0),
            new Descriptor("expression/progression", "Contains a gradual advancement in difficulty or concept across the map.", null),
            new Descriptor("expression/repetition", "Features the use of recognizable identical patterns or gameplay elements.", null),
            new Descriptor("expression/simple", "Accessible and straightforward map design.", null),
            new Descriptor("gimmick/2B", "Includes gameplay elements with two or more objects placed simultaneously. The term originates from a Chinese transliteration of 'idiot'.", null),
            new Descriptor("gimmick/LN inverse", "Maps that feature long note holds that emphasize constant holds and releases in quick succession. Most distinct feature of Inverse is the “negative spaces” in the patterning.", 3),
            new Descriptor("gimmick/aspire", "Uses glitches to provide gameplay or visual effects that are otherwise impossible to achieve, originating from the annual Aspire mapping contest.", 0),
            new Descriptor("gimmick/barlines", "A map that makes use of barlines to enhance visuals or replace notes.", 1),
            new Descriptor("gimmick/circle only", "Restricts object choice to circles only.", 0),
            new Descriptor("gimmick/delay", "Maps that feature high snap streams based on the song’s delayed sound effect. ", 3),
            new Descriptor("gimmick/dodge the beat", "A map where the player needs to avoid every object.", 2),
            new Descriptor("gimmick/long sliders", "A map that uses sliders for an extended period of time, having regular gameplay around catching juice drops and droplets instead of fruits.", 2),
            new Descriptor("gimmick/memory", "A map designed around a memorization concept.", null),
            new Descriptor("gimmick/mirrored", "A map that features patterns that are mirrored on an axes in quick successions.", 1),
            new Descriptor("gimmick/ninja spinners", "Features spinners that are very short in duration.", 0),
            new Descriptor("gimmick/no hyperdashes", "A map that doesn’t use hyperdashes even if allowed for its respective difficulty.", 2),
            new Descriptor("gimmick/playfield constraint", "Restricts object placement to a certain part of the playfield.", 0),
            new Descriptor("gimmick/reversed", "A map using reversed patterns in a regularly consecutive manner.", 1),
            new Descriptor("gimmick/slider only", "Restricts object choice to sliders only.", 0),
            new Descriptor("gimmick/spinner-heavy", "A map that features heavy usage of spinners.", 2),
            new Descriptor("gimmick/storyboard", "Includes a storyboard that changes how the map is played, usually by changing a map's visuals by using storyboard elements in place of showing the map's hitobjects.", null),
            new Descriptor("gimmick/tag", "Includes gameplay designed for the multiplayer tag mode, where multiple players complete a map co-operatively.", null),
            new Descriptor("gimmick/video", "Employs patterning that closely references the included background video.", null),
            new Descriptor("gimmick/yellow notes", "A map featuring frequent use of extremely short sliders to simulate ghost notes.", 1),
            new Descriptor("jumps/back and forth", "Frequent use of back and forth patterns.", 0),
            new Descriptor("jumps/cross-screen", "Frequent use of jumps with a lot of spacing, usually placed on opposite sides of the playfield.", 0),
            new Descriptor("jumps/freeform", "Frequent use of jumps without distinct patterning.", 0),
            new Descriptor("jumps/linear", "Patterns that require the player to move continuously in a straight or nearly straight line.", 0),
            new Descriptor("jumps/sharp", "Patterns with heavy use of sharp angle movement.", 0),
            new Descriptor("jumps/squares", "Frequent use of square patterns.", 0),
            new Descriptor("jumps/stamina", "Tests a player's ability to aim spaced jumps over long periods of time.", 0),
            new Descriptor("jumps/stars", "Frequent use of star/pentagon patterns.", 0),
            new Descriptor("jumps/triangles", "Frequent use of triangular patterns.", 0),
            new Descriptor("jumps/wide", "Patterns with heavy use of wide angle movement.", 0),
            new Descriptor("meta/accelerating bpm", "A song featuring progressively increasing tempo.", null),
            new Descriptor("meta/collab", "A map with two or more associated mappers.", null),
            new Descriptor("meta/mega collab", "A map with 8 or more associated mappers.", null),
            new Descriptor("meta/multi-song", "A map containing multiple songs.", null),
            new Descriptor("meta/swing", "A song with prominent use of swing rhythms.", null),
            new Descriptor("meta/time signatures", "A song featuring many changes in time signature or uses an uncommon time signature.", null),
            new Descriptor("meta/variable timing", "Contains multiple timing points, usually required for songs not recorded to a metronome.", null),
            new Descriptor("reading/overlaps", "Contains patterns where overlapped objects make determining note order and/or timing difficult.", 0),
            new Descriptor("reading/perfect stacks", "Features perfectly overlapped stacked notes using low stack leniency.", 0),
            new Descriptor("reading/visually dense", "Contains patterns where the amount of visible notes makes determining note order and/or timing difficult.", 0),
            new Descriptor("skillset/alt", "Colloquial term for maps which use rhythms that encourage the player to alternate notes. Typically distinct from burst or stream maps.", 0),
            new Descriptor("skillset/gimmick", "Distinct or obscure gameplay elements that cannot be categorised with common skillsets.", null),
            new Descriptor("skillset/jumps", "Focuses heavily on jumps, i.e. circles spaced far apart that require the player to move towards, slow down to hit, then speed up to move towards the next object.", 0),
            new Descriptor("skillset/precision", "Colloquial term for maps which require fine, precise movement to aim correctly. Typically refers to maps with circle sizes above and including 6.", 0),
            new Descriptor("skillset/precision", "Colloquial term for maps which require fine, precise movement to catch fruits. Typically refers to maps with circle sizes above and including 6.", 2),
            new Descriptor("skillset/reading", "Tests a player's reading skill, i.e. patterns that obfuscate note order and/or timing.", null),
            new Descriptor("skillset/speedjack", "Maps that feature shorter jack sequences, characterized by the faster timeframe between consecutive stacked notes.", 3),
            new Descriptor("skillset/streams", "Patterns requiring continuous note hits, typically more than 9 notes.", null),
            new Descriptor("skillset/tech", "Tests uncommon skills.", 0),
            new Descriptor("skillset/tech", "A map that frequently makes use of complex snaps.", 1),
            new Descriptor("skillset/tech", "A map with the focus on lots of 1/4 sliders, hypersliders and stacks.", 2),
            new Descriptor("skillset/tech", "A map that frequently makes use of complex snaps.", 3),
            new Descriptor("skillset/wristjack", "Fast and/or fairly dense chordjack maps, whose optimal playing technique involves the use of the player’s wrist movements.", 3),
            new Descriptor("sliders/complex slidershapes", "Uses a large variety of slider designs.", 0),
            new Descriptor("sliders/complex sv", "Changes slider velocity by large amounts in order to test the player's reading and aim ability.", 0),
            new Descriptor("sliders/complex sv", "Changes slider velocity by large amounts in order to test the player's reading ability.", 1),
            new Descriptor("sliders/complex sv", "Changes slider velocity by large amounts in order to test the player's reading ability.", 3),
            new Descriptor("sliders/high sv", "Features prominent high slider velocity usage as a key part of map design.", null),
            new Descriptor("sliders/low sv", "Features prominent low slider velocity usage as a key part of map design.", null),
            new Descriptor("streams/bursts", "Patterns requiring consecutively tapping 5-9 note groups.", null),
            new Descriptor("streams/cutstreams", "Streams in which the spacing of certain notes is much larger than the rest of the stream.", 0),
            new Descriptor("streams/doubles", "Patterns requiring consecutively tapping 2 note groups.", null),
            new Descriptor("streams/flow aim", "Patterns with fully continuous cursor movement, usually due to a combination of wide angles and little time between objects.", 0),
            new Descriptor("streams/quads", "Patterns requiring consecutively tapping 4 note groups.", null),
            new Descriptor("streams/spaced streams", "Streams with large spacing, typically ones where the notes don't overlap.", 0),
            new Descriptor("streams/speed", "A map that requires constant tapping at high BPMs.", null),
            new Descriptor("streams/stamina", "Tests a player's ability to tap dense rhythms over long periods of time.", 0),
            new Descriptor("streams/stamina", "Tests a player's ability to tap dense rhythms over long periods of time.", 1),
            new Descriptor("streams/stamina", "Tests a player's ability to tap dense rhythms over long periods of time.", 3),
            new Descriptor("style/LN coordination", "Maps which require holding multiple long notes simultaneously while hitting other patterns.", 3),
            new Descriptor("style/LN density", "Maps that feature dense long note streams without breaks.", 3),
            new Descriptor("style/LN mixed ", "Maps that make use of multiple long note patterning styles.", 3),
            new Descriptor("style/LN release", "Maps that make use of different long note holds ending.", 3),
            new Descriptor("style/N+1", "A specific type of playstyle where the leftmost column is mapped independently from the rest of the columns, which otherwise form a standard playstyle.", 3),
            new Descriptor("style/avant-garde", "Employs boundary-pushing and experimental philosophies to map design, often foregoing gameplay and aesthetic conventions to extreme measures.", null),
            new Descriptor("style/chordjack", "Maps that feature evenly spaced chords, with several consecutive notes stacked on the same columns.", 3),
            new Descriptor("style/chordstream", "Maps that make use of streams with a mix of differently-sized chords", 3),
            new Descriptor("style/clean", "Visually uncluttered and organised patterns, often involving few overlaps and equal visual spacing between objects.", 0),
            new Descriptor("style/convert", "A map that imitates the converted maps from osu!.", 1),
            new Descriptor("style/convert", "A map that imitates the converted maps from osu!, where the structure and distances are irregular.", 2),
            new Descriptor("style/distance snap", "Uses osu's in-built distance snap feature for most/all of the map.", 0),
            new Descriptor("style/double bpm", "A map that plays at double the speed than what the BPM indicates.", 1),
            new Descriptor("style/dump", "Maps that use groups of objects focusing more on the extension and intensity of the sounds, in contrast with using individual notes to follow each's sound timing accurately.", 3),
            new Descriptor("style/finisher-heavy", "Features finishers used in an unconventional manner or in large amounts.", 1),
            new Descriptor("style/freeform", "An unrestrained and loose approach towards visual structure.", 0),
            new Descriptor("style/generic hybrid", "Maps that feature the combination of both straightforward rice and Long Notes patterning.", 3),
            new Descriptor("style/geometric", "Incorporates geometric shapes within the map's visual design.", 0),
            new Descriptor("style/grid snap", "Objects are placed along a square grid, typically using osu!'s in-built grid snap feature.", 0),
            new Descriptor("style/handstream", "Stream with a mix of 3-note sized chords", 3),
            new Descriptor("style/hexgrid", "Objects are placed along a hexagonal grid.", 0),
            new Descriptor("style/jumpstream", "Stream with a mix of 2-note sized chords", 3),
            new Descriptor("style/longjack", "Maps that feature long chains of consecutive notes on the same column.", 3),
            new Descriptor("style/messy", "Visually chaotic and intentionally disorganised patterns, often involving many overlaps and unequal visual spacing between objects.", 0),
            new Descriptor("style/mixed rice", "Maps that make use of multiple rice patterning styles.", 3),
            new Descriptor("style/mono-heavy", "Features monos used in large amounts.", 1),
            new Descriptor("style/o2jam", "Map that mimics traditional mapping techniques usually found in O2jam charts.", 3),
            new Descriptor("style/quadstream", "Stream with a mix of 4-note sized chords", 3),
            new Descriptor("style/symmetrical", "Employs symmetry within the map design, often mirroring elements along the horizontal centreline.", 0),
            new Descriptor("style/taikosu", "A map designed with both osu! and osu!taiko in mind.", 1),
            new Descriptor("style/tiebreaker", "Maps that contain most of the skill sets from different categories, and are usually longer than 5 minutes.", 3),
            new Descriptor("style/tnt", "A map that imitates the mapping style in Taiko No Tatsujin.", 1),
            new Descriptor("style/vocal", "Patterning that focuses mainly on vocals.", 1),
            new Descriptor("tech/aim control", "Patterns with velocity or direction changes which strongly go against a player's natural movement pattern.", 0),
            new Descriptor("tech/antiflow", "A map focused on strong direction or velocity changes that go against a player's natural movement pattern.", 2),
            new Descriptor("tech/complex snap", "Maps that feature prominent usage of mixed or unusual snap divisors.", 1),
            new Descriptor("tech/complex snap", "Maps that feature prominent usage of mixed or unusual snap divisors.", 2),
            new Descriptor("tech/complex snap", "Maps that feature prominent usage of mixed or unusual snap divisors.", 3),
            new Descriptor("tech/finger control", "Uses complex applications of rhythms in order to test the player's tapping ability.", 0),
            new Descriptor("tech/flow", "A map focused on natural and intuitive movement patterns.", 2),
            new Descriptor("tech/hyperwalks", "A map which makes use of hyperdashes that require the player to walk, as otherwise, you will overshoot them.", 2),
            new Descriptor("tech/jump", "A map that focuses on 1/2 constant dashes or hyperdashes.", 2),
            new Descriptor("tech/slider tech", "Tests uncommon skills involving sliders, such as heavy use of kicksliders or aim on complex slidershapes.", 0),
            new Descriptor("tech/technical hybrid", "Maps that feature the combination of both technical rice and Long Notes patterning.", 3),
            new Descriptor("tech/wiggles", "A map with a focus on quick directional changes.", 2),
        };
    }
}
